#!/bin/bash
Applications    Documents   Dropbox Movies Pictures Applications    Documents   Dropbox Movies Pictures
Applications    Documents   Dropbox Movies Pictures Desktop Downloads   Library Music Public
